import json
import os
from pathlib import Path

from dotenv import load_dotenv

from agents.base import Agent

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# This code is generated by the agent and executed INSIDE the Daytona sandbox.
# {product_json} and {country} are interpolated before upload.
SANDBOX_CODE = """
import json

product = {product_json}
country = {country!r}
declared_value_jpy = 30000

# Hardcoded destination rules (hackathon demo data, not legal advice)
RULES = {{
    "Germany":   {{"blade_cap_cm": None, "duty_rate": 0.085, "carry": "checked luggage OK", "courier": "DHL Express"}},
    "USA":       {{"blade_cap_cm": None, "duty_rate": 0.0,   "carry": "checked luggage OK", "courier": "FedEx International Priority"}},
    "France":    {{"blade_cap_cm": None, "duty_rate": 0.085, "carry": "checked luggage OK", "courier": "DHL Express"}},
    "UK":        {{"blade_cap_cm": 18.0, "duty_rate": 0.08,  "carry": "blades >18cm cannot be carried, must ship", "courier": "UPS Worldwide Expedited"}},
    "Australia": {{"blade_cap_cm": None, "duty_rate": 0.05,  "carry": "checked luggage OK, declare at border", "courier": "FedEx International Priority"}},
}}

category = product.get("type", "").lower()
material = product.get("material", "").lower()
cutlery_terms = ("knife", "knives", "cutlery", "blade", "santoku", "cleaver", "chef")
if any(term in category for term in cutlery_terms) or "steel" in material:
    hs_code = "8211"
    item_kind = "kitchen knives"
else:
    hs_code = "6912"
    item_kind = "ceramic tableware"

rules = RULES.get(country, {{"blade_cap_cm": None, "duty_rate": 0.10, "carry": "ship only", "courier": "DHL Express"}})

duty_estimate_jpy = round(declared_value_jpy * rules["duty_rate"])

if rules["blade_cap_cm"] is not None:
    blade_rule = f"{{country}} restricts carry of blades over {{rules['blade_cap_cm']}}cm"
else:
    blade_rule = f"{{country}} has no specific blade-length cap for kitchen knives"

verdict = (
    f"{{item_kind.capitalize()}} (HS {{hs_code}}) to {{country}}: {{rules['carry']}}. "
    f"{{blade_rule}}. Estimated duty on JPY {{declared_value_jpy:,}}: JPY {{duty_estimate_jpy:,}} "
    f"({{rules['duty_rate']*100:.1f}}%). Ship via {{rules['courier']}}."
)

result = {{
    "hs_code": hs_code,
    "carry_vs_ship": rules["carry"],
    "blade_length_rule": blade_rule,
    "duty_estimate": f"JPY {{duty_estimate_jpy:,}} on declared JPY {{declared_value_jpy:,}}",
    "recommended_courier": rules["courier"],
    "verdict": verdict,
}}
print(json.dumps(result))
"""


class ExportIntelligenceAgent(Agent):
    name = "Export Intelligence"

    def run(self, context: dict) -> dict:
        self.log("Computing export feasibility in Daytona sandbox")

        from daytona import Daytona, DaytonaConfig

        product = context["product_analysis"]
        country = context.get("buyer_country", "Germany")

        code = SANDBOX_CODE.format(product_json=json.dumps(product), country=country)

        daytona = Daytona(DaytonaConfig(api_key=os.environ["DAYTONA_API_KEY"]))
        sandbox = daytona.create(timeout=120)
        try:
            response = sandbox.process.code_run(code, timeout=120)
        finally:
            sandbox.delete()

        output = response.result.strip()
        try:
            data = json.loads(output)
        except json.JSONDecodeError:
            print("Raw sandbox output (JSON parse failed):")
            print(output)
            raise

        self.log(data["verdict"])
        return {"export_intelligence": data, "generated_code": code}
